Updated to use easymock 5.0.1, dropped the support for Scala 2.10.7 as class generated by Scala 2.10 seems not playing well with easymock 5.0, got the following error when running test:
java.lang.IncompatibleClassChangeError: org.scalatestplus.easymock.EasyMockSugarSpec$$anonfun$17$$anon$1 and org.scalatestplus.easymock.EasyMockSugarSpec$$anonfun$17$$anon$1$$anonfun$3$OneFish$3 disagree on InnerClasses attribute